export const text = 'Once  upon a time, in a land far, far away, there was a majestic kingdom called Youlandia. This kingdom was known for its breathtaking landscapes, vibrant culture, and wise rulers.' +
    'In Youlandia, the sun shone brightly, casting a golden glow over the rolling hills and crystal-clear lakes. The air was filled with the sweet scent of blooming flowers, and the sound of birds chirping echoed through the lush forests.' +
    'The people of Youlandia were known for their kindness, generosity, and creativity. They were skilled craftsmen, talented artists, and brilliant inventors. Every corner of the kingdom was adorned with beautiful sculptures, stunning paintings, and innovative gadgets that showcased their boundless imagination.' +
    'he capital city of Youlandia, called Lumosville, was a bustling metropolis where people from all walks of life came together. The streets were lined with colorful buildings, bustling marketplaces, and enchanting cafes where the aroma of freshly brewed coffee filled the air.' +
    'The royal palace, situated on a hill overlooking the city, was a sight to behold. Its grand architecture, adorned with intricate carvings and sparkling gemstones, mesmerized all who laid eyes upon it. Inside the palace, the royal family governed with wisdom and compassion, ensuring the prosperity and happiness of their subjects.' +
    'But Youlandia was not without its challenges. Fierce dragons roamed the outskirts of the kingdom, posing a threat to the safety of its people. Brave knights were tasked with protecting the kingdom, embarking on daring quests to slay the dragons and restore peace.' +
    'Despite these challenges, the people of Youlandia remained resilient and united. They believed in the power of love, courage, and friendship to overcome any obstacle. Together, they celebrated festivals, shared stories around campfires, and danced under the starry night sky.' +
    'In Youlandia, the sun shone brightly, casting a golden glow over the rolling hills and crystal-clear lakes. The air was filled with the sweet scent of blooming flowers, and the sound of birds chirping echoed through the lush forests.' +
    'The people of Youlandia were known for their kindness, generosity, and creativity. They were skilled craftsmen, talented artists, and brilliant inventors. Every corner of the kingdom was adorned with beautiful sculptures, stunning paintings, and innovative gadgets that showcased their boundless imagination.' +
    'he capital city of Youlandia, called Lumosville, was a bustling metropolis where people from all walks of life came together. The streets were lined with colorful buildings, bustling marketplaces, and enchanting cafes where the aroma of freshly brewed coffee filled the air.' +
    'The royal palace, situated on a hill overlooking the city, was a sight to behold. Its grand architecture, adorned with intricate carvings and sparkling gemstones, mesmerized all who laid eyes upon it. Inside the palace, the royal family governed with wisdom and compassion, ensuring the prosperity and happiness of their subjects.' +
    'But Youlandia was not without its challenges. Fierce dragons roamed the outskirts of the kingdom, posing a threat to the safety of its people. Brave knights were tasked with protecting the kingdom, embarking on daring quests to slay the dragons and restore peace.' +
    'Despite these challenges, the people of Youlandia remained resilient and united. They believed in the power of love, courage, and friendship to overcome any obstacle. Together, they celebrated festivals, shared stories around campfires, and danced under the starry night sky.' +
    'In Youlandia, the sun shone brightly, casting a golden glow over the rolling hills and crystal-clear lakes. The air was filled with the sweet scent of blooming flowers, and the sound of birds chirping echoed through the lush forests.' +
    'The people of Youlandia were known for their kindness, generosity, and creativity. They were skilled craftsmen, talented artists, and brilliant inventors. Every corner of the kingdom was adorned with beautiful sculptures, stunning paintings, and innovative gadgets that showcased their boundless imagination.' +
    'he capital city of Youlandia, called Lumosville, was a bustling metropolis where people from all walks of life came together. The streets were lined with colorful buildings, bustling marketplaces, and enchanting cafes where the aroma of freshly brewed coffee filled the air.' +
    'The royal palace, situated on a hill overlooking the city, was a sight to behold. Its grand architecture, adorned with intricate carvings and sparkling gemstones, mesmerized all who laid eyes upon it. Inside the palace, the royal family governed with wisdom and compassion, ensuring the prosperity and happiness of their subjects.' +
    'But Youlandia was not without its challenges. Fierce dragons roamed the outskirts of the kingdom, posing a threat to the safety of its people. Brave knights were tasked with protecting the kingdom, embarking on daring quests to slay the dragons and restore peace.' +
    'Despite these challenges, the people of Youlandia remained resilient and united. They believed in the power of love, courage, and friendship to overcome any obstacle. Together, they celebrated festivals, shared stories around campfires, and danced under the starry night sky.' +
    'In Youlandia, the sun shone brightly, casting a golden glow over the rolling hills and crystal-clear lakes. The air was filled with the sweet scent of blooming flowers, and the sound of birds chirping echoed through the lush forests.' +
    'The people of Youlandia were known for their kindness, generosity, and creativity. They were skilled craftsmen, talented artists, and brilliant inventors. Every corner of the kingdom was adorned with beautiful sculptures, stunning paintings, and innovative gadgets that showcased their boundless imagination.' +
    'he capital city of Youlandia, called Lumosville, was a bustling metropolis where people from all walks of life came together. The streets were lined with colorful buildings, bustling marketplaces, and enchanting cafes where the aroma of freshly brewed coffee filled the air.' +
    'The royal palace, situated on a hill overlooking the city, was a sight to behold. Its grand architecture, adorned with intricate carvings and sparkling gemstones, mesmerized all who laid eyes upon it. Inside the palace, the royal family governed with wisdom and compassion, ensuring the prosperity and happiness of their subjects.' +
    'But Youlandia was not without its challenges. Fierce dragons roamed the outskirts of the kingdom, posing a threat to the safety of its people. Brave knights were tasked with protecting the kingdom, embarking on daring quests to slay the dragons and restore peace.' +
    'Despite these challenges, the people of Youlandia remained resilient and united. They believed in the power of love, courage, and friendship to overcome any obstacle. Together, they celebrated festivals, shared stories around campfires, and danced under the starry night sky.' +
    'In Youlandia, the sun shone brightly, casting a golden glow over the rolling hills and crystal-clear lakes. The air was filled with the sweet scent of blooming flowers, and the sound of birds chirping echoed through the lush forests.' +
    'The people of Youlandia were known for their kindness, generosity, and creativity. They were skilled craftsmen, talented artists, and brilliant inventors. Every corner of the kingdom was adorned with beautiful sculptures, stunning paintings, and innovative gadgets that showcased their boundless imagination.' +
    'he capital city of Youlandia, called Lumosville, was a bustling metropolis where people from all walks of life came together. The streets were lined with colorful buildings, bustling marketplaces, and enchanting cafes where the aroma of freshly brewed coffee filled the air.' +
    'The royal palace, situated on a hill overlooking the city, was a sight to behold. Its grand architecture, adorned with intricate carvings and sparkling gemstones, mesmerized all who laid eyes upon it. Inside the palace, the royal family governed with wisdom and compassion, ensuring the prosperity and happiness of their subjects.' +
    'But Youlandia was not without its challenges. Fierce dragons roamed the outskirts of the kingdom, posing a threat to the safety of its people. Brave knights were tasked with protecting the kingdom, embarking on daring quests to slay the dragons and restore peace.' +
    'Despite these challenges, the people of Youlandia remained resilient and united. They believed in the power of love, courage, and friendship to overcome any obstacle. Together, they celebrated festivals, shared stories around campfires, and danced under the starry night sky.' +
    'And so, the story of Youlandia continues to unfold, filled with adventure, magic, and the triumph of the human spirit. It serves as a reminder that no matter how big or small, every individual has the power to make a difference and create a world filled with beauty and joy.';